class Solution {
        Set<String> set = new HashSet<>();

            public List<String> removeInvalidParentheses(String s) {
                    int left = 0;
                            int right = 0;

                                    for (char ch : s.toCharArray()) {
                                                if (ch == '(') {
                                                                left++;
                                                                            } else if (ch == ')') {
                                                                                            if (left > 0) {
                                                                                                                left--;
                                                                                                                                } else {
                                                                                                                                                    right++;
                                                                                                                                                                    }
                                                                                                                                                                                }
                                                                                                                                                                                        }

                                                                                                                                                                                                solve(s, 0, left, right, 0, new StringBuilder());

                                                                                                                                                                                                        return new ArrayList<>(set);
                                                                                                                                                                                                            }

                                                                                                                                                                                                                public void solve(String s, int index, int leftRemove,
                                                                                                                                                                                                                                      int rightRemove, int balance,
                                                                                                                                                                                                                                                            StringBuilder curr) {

                                                                                                                                                                                                                                                                    if (index == s.length()) {
                                                                                                                                                                                                                                                                                if (leftRemove == 0 && rightRemove == 0 && balance == 0) {
                                                                                                                                                                                                                                                                                                set.add(curr.toString());
                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                        return;
                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                        char ch = s.charAt(index);

                                                                                                                                                                                                                                                                                                                                                if (ch == '(' && leftRemove > 0) {
                                                                                                                                                                                                                                                                                                                                                            solve(s, index + 1, leftRemove - 1,
                                                                                                                                                                                                                                                                                                                                                                              rightRemove, balance, curr);
                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                              if (ch == ')' && rightRemove > 0) {
                                                                                                                                                                                                                                                                                                                                                                                                          solve(s, index + 1, leftRemove,
                                                                                                                                                                                                                                                                                                                                                                                                                            rightRemove - 1, balance, curr);
                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                            curr.append(ch);

                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (ch != '(' && ch != ')') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                solve(s, index + 1, leftRemove,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  rightRemove, balance, curr);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          } else if (ch == '(') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      solve(s, index + 1, leftRemove,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        rightRemove, balance + 1, curr);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } else if (balance > 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            solve(s, index + 1, leftRemove,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              rightRemove, balance - 1, curr);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              curr.deleteCharAt(curr.length() - 1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
